### PR TITLE
Correcting incorrect integer equivalents for ECH and outer_extensions

### PR DESCRIPTION
**Pull request by sudheesh001**
Signed-off-by: Sudheesh Singanamalla <sudheesh@cloudflare.com>

### CODE REVIEW

**Comment by sudheesh001** [comment]
@chris-wood This is ready for review.

**Review by chris-wood — APPROVED** [review]

**Comment by davidben** [comment]
I don't think this is right. It's not an integer equivalent but a max value for sizing the enum.
https://tools.ietf.org/html/rfc8446#section-3.5

(The TLS presentation syntax is sometimes confusing.)

**Comment by chris-wood** [comment]
Oh, well that's annoying. And confusing. I'll revert this.

**Comment by sudheesh001** [comment]
Ah that was confusing. Apologies.

**Pull request merged**
