### PR TITLE
Use new RRType instead of TXT with a custom prefix

### PR DESCRIPTION
**Pull request by chris-wood**
Subsumes #73 and #108.

### CODE REVIEW

**Comment by mcmanus** [comment]
lgtm

**Comment by ValZapod** [comment]
@chris-wood @kazuho @mcmanus 
What the... So all already working eSNI in Cloudflare is already outdated? Do you understand how difficult it will be to get new IN ESNI in Bind and Knot and even in dig utility? Do you understand that while IN txt is working in all OS, IN ESNI will not work in any of them (system resolver, I mean)? Do you understand that you use for ESNI RR 0xff9f (which is 65439), so it is reserved for private use in IANA?
Solution for this. Can you please use both of them?

**Comment by mcmanus** [comment]
>   Internet-Drafts are draft documents valid for a maximum of six months
 >  and may be updated, replaced, or obsoleted by other documents at any
  > time.  It is inappropriate to use Internet-Drafts as reference
  > material or to cite them other than as "work in progress."

**Comment by Viktor45** [comment]
this is good for wiretapping for easy to drop all ESNI with DPI for SNI downgrade

**Pull request merged**
