### PR TITLE
Pick from an unassigned range.

### LINKED ISSUE #322: Tidy up all codepoints before -08
Note to self. Let's pick a set and range that works.

### PR DESCRIPTION
**Pull request by chris-wood**
Closes #322.

cc @davidben, @cjpatton

### CODE REVIEW

**Review by cjpatton — COMMENTED** [review]
What will be our policy if we need to add additional extension points, e.g., to address #264? Do we start incrementing from `0xfe00`?

**Comment by chris-wood** [comment]
> What will be our policy if we need to add additional extension points, e.g., to address #264? Do we start incrementing from 0xfe00?

Yeah, that's what I figured. I doubt we'll need more than 8, but we can pick a different range if that works?

**Comment by cjpatton** [comment]
Yeah, this works for me. I don't see any reason why we should keep the code points dense.

**Review by cjpatton — APPROVED** [review]

**Review by davidben — COMMENTED** [review]
Sure, those work. I usually `random.randint(0, 0xffff)` to avoid thinking about it, but whatever. :-)

**Review by davidben — APPROVED** [review]

**Pull request merged**
