### PR TITLE
Drop fixed key_share requirement to avoid nonce reuse and better align with HPKE

### PR DESCRIPTION
**Pull request by chris-wood**
This is an alternative to #168, wherein we use fresh DH keys each time and avoid changing the key/iv derivation labels across CH messages.

### CODE REVIEW

**Comment by chris-wood** [comment]
Ping @ekr @kazuho

**Comment by kazuho** [comment]
IIUC, this is a trade-off issue. Therefore I do not have a strong preference, though my weak prerefence goes to keeping the design as-is. The reasons are as follows.

The benefit of the proposed change is that it frees client from buffering the content of the ESNI extension (after encryption), when using a building block that does not support reusing the same public key pair. Though, we might argue that even with this change, clients might still want to buffer the extension for possible retransmission rather than doing another public key operation in case of receiving a HRR.

The downside of the proposed change is that it might require the server to do another public key operation when verifying the ESNI extension found in ClientHello send in response to HelloRetryRequest. Current design, by requiring the keys to be identical, allows a server to validate the indifference of the ESNI extension without actually deciphering the payload.

One of the role of HRR is to mitigate attacks. When under attack, I believe that servers would be reluctant to do an additional public key operation. Therefore, to me it seems that the proposed change would incentivize the server to skip the verification of the ESNI extension sent in response to HRR.

Comparing the benefit and the downside, my weak preference goes to retaining the design as-is, because as I stated, I think that clients would be (mostly) fine with the design, and under the assumption that it is beneficial to encourage servers to validate the ESNI extension sent in response to HRR.

**Comment by martinthomson** [comment]
I share @kazuho's concerns.  The use of a different label after HRR is annoying, but not that difficult to manage.  You could also include the session transcript up to (but not including) the ClientHello, but you need something.

Flipping the shares is a costly exercise.  You might have to do it anyway, but if you don't, then you can save some computation.  I can definitely see the value in stuffing the decrypted SNI into the cookie so that you don't have to redo the ESNI piece.

**Comment by chris-wood** [comment]
The benefit of this approach is primarily simplicity for clients and HPKE alignment. (HPKE generates a fresh key each time, so we couldn’t adopt it as is unless that draft changed.) I agree that the cost of yet another DH operation is not great, though I’m not yet convinced it’s enough to disqualify this change.

**Comment by ekr** [comment]
Hmm... I'm not sure I follow all of this.

You can't store the decrypted SNI in the cookie because you need to re-verify the AEAD which is tied to the new key share. You can of course stuff Z in the cookie, though, so I'm not sure how much difference this makes. With that said, in the common case (one server) you are going to have a uniform config so you don't need to decrypt ESNI at all in order to send HRR, no?

As I mentioned to @chris-wood, this is tied to using HPKE -- if we decide to do that, we are going to either have to adopt a "fresh DH" version or extend the HPKE API to have some sort of key reuse + salt.

**Comment by kazuho** [comment]
@chris-wood 
> The benefit of this approach is primarily simplicity for clients and HPKE alignment. (HPKE generates a fresh key each time, so we couldn’t adopt it as is unless that draft changed.)

I think our disagreement is if current provision deters the adoption of HPKE.

I'm not familiar with HPKE and I could be wrong, but it is my understanding that the current design can use a public key crypto engine that uses a fresh key for every operation.

That is because the ESNI extension sent in the 2nd ClientHello is a "retransmission." Server's public key pair does not change, and ClientHello.random does not change. Therefore, when sending the first ClientHello, a client can just keep the encrypted payload of ESNI extension. Then, when it receives a HelloRetryRequest, it would retransmit the buffered payload of the ESNI extension.

**Comment by ekr** [comment]
@kazuho: I don't believe that this will work because the client's KeyShare will likely change in HRR, and it is AAD to the ESNI Extension, thus the ciphertext will change. Or am I confused?

**Comment by kazuho** [comment]
@ekr Ah I missed that (and picotls has a bug!). Thank you for pointing that out.

That said, I think that the @martinthomson's argument (which was also the rest of my argument) still holds. If we want servers to verify the ESNI extension sent in the 2nd ClientHello, it is benefical to require the clients to use the same public key.

Because, then, a server can retain the key and iv (either in it's state or in Cookie), and just do the AEAD operation to validate the ESNI extension found in the 2nd ClientHello. If we think that such check can be avoided (even though we would not encourage that), I think I'd be fine with allowing the client to change the public key.

**Comment by ekr** [comment]
@kazuho nitpicking: you will need to retain Z, I think.

With that said, how do you think we would handle the transition to HPKE?

**Comment by chris-wood** [comment]
@kazuho @grittygrease how do you want to proceed here?

**Comment by davidben** [comment]
(This comment ended up long, so I'm splitting it into sections.)

**Why check the second ClientHello**

> If we think that such check can be avoided (even though we would not encourage that), I think I'd be fine with allowing the client to change the public key.

If the server does not check the second ClientHello, then cut-and-paste attacks are possible against client/server pairs which hit HelloRetryRequest because we lose the binding between ESNI and the key shares that were actually used. (It really would be cleaner if we just stuffed something into the key schedule, but then the client needs to trial-decrypt or we need a cleartext "yes, I used ESNI" signal.)

For completeness, deployments which allow different services to have different version, cipher, or group preferences need to process ESNI on the first ClientHello because resolving HRR requires those preferences. Of course, services with different preferences will partition the anonymity sets a little bit, but enough deployments expect to be able to vary TLS parameters this way that I think we need to allow for this. (BoringSSL, for instance, resolves SNI on the first ClientHello.)

**Split mode**

On that note, split mode and HRR are a little messy. Possibilities I can see:

1. Dispatch happens at second ClientHello. Frontend and backend must agree on HRR-sensitive parameters, and backend gets a handshake transcript from the frontend.
2. Dispatch happens at first ClientHello, but frontend and backend agree on enough of TLS parameters that frontend can sniff HelloRetryRequest + second ClientHello (technically a [protocol invariant](https://tools.ietf.org/html/rfc8446#section-9.3) violation) to check the ESNI.
3. Backend and frontend both have ESNI keys. This contradicts #169.

**Near-attack**

Finally, I think there's one more issue here with changing the key share which, while not fatal, is rather a headache. Suppose we went with this PR. Here is a near-attack:

1. Attacker observes an ESNI-ful HRR-ful connection. Let CH1 and CH2 be the first and second ClientHellos.
2. Attacker wants to determine if CH1/CH2's ESNI contained hostname H. (It can repeat this process with different guesses.)
3. Attacker makes a connection to the server. It replays CH1 and gets an HRR.
4. Attacker sends its own second ClientHello with its own key shares and an ESNI record containing H.
5. If H matched CH1's ESNI, the server will accept the connection and continue. If it mismatched, the server will fail with an alert.

This is only a near-attack because ClientESNIInner contains a nonce the attacker cannot guess, so even if it matched the hostname, it cannot match the nonce. But this means the server must perform the comparison in constant-time (attacker can repeat steps 3-5 all it wants) and the nonce is even more load-bearing in a subtle way.

Example of subtlety: In both "server must check CH2" PRs, it is easy for the server to ignore it and no one notices. One could imagine saying the ESNI nonce must change in CH2, so the server *at least* doesn't ignore it. But that would turn this near-attack into an actual attack. Whereas I believe the same-key version avoids all of this.

**Changing the key schedule**

It seems we're in this mess because we've bound ESNI to the handshake in a roundabout way rather than injecting the key into the key schedule. I believe this originally was to aid split mode, but we've since added this nonce anyway, so having frontend pass the key schedule addition into the backend is plausible. Perhaps this is worth reconsidering? Some thoughts:

First, there isn't a slot in the key schedule for this. I think that's fine though, as long as we change the label. Here's one possibility:

```
             0
             |
             v
   PSK ->  HKDF-Extract = Early Secret
             |
             +-----> Derive-Secret(...)
             |                     = binder_key
             |                     = client_early_traffic_secret
             |                     = early_exporter_master_secret
             v
       Derive-Secret(., "derived", "")
             |
             v
   (EC)DHE -> HKDF-Extract
             |
             v
       Derive-Secret(., "esni nonce", "")
             |
             v
ESNI nonce -> HKDF-Extract = Handshake Secret
             |
             +-----> Derive-Secret(...)
             |                     = client_handshake_traffic_secret
             |                     = server_handshake_traffic_secret
             v
            ...
 ```
(Arguably all the "derived" labels should have had names.)

The second issue is how to signal it on the client. I see two options:

1. Cleartext signal in ServerHello. This violates "do not stick out" and makes the GREASE extensions totally useless.
2. The client computes both server_handshake_traffic_secret values and trial-decrypts to figure out which one to use. This is trial decryption and non-destructive trial-decryption at that, so it's rather a headache. (On the plus side, it only needs to be done on the first handshake record.)

Neither of these is very satisfactory but, then again, nor are our other two options. :-/

**Conclusion**

Everything is a mess.

**Comment by kazuho** [comment]
@chris-wood 
> how do you want to proceed here?

As we do not have time, I think we should merge #168 (it does not change the client behavior, and I think we agree that requiring the server to validate the ESNI extension found in 2nd CH is a good idea), while keeping this PR open for further discussion.

**Pull request closed without merging**
